"""Shared primitives: registry, errors, result type."""

from citnega.packages.shared.errors import (
    AdapterError,
    AdapterInitError,
    ApprovalDeniedError,
    ApprovalTimeoutError,
    ArtifactError,
    CallableDepthError,
    CallableError,
    CallableNotFoundError,
    CallablePolicyError,
    CallableTimeoutError,
    CallableValidationError,
    CitnegaError,
    ConfigError,
    FrameworkRunnerError,
    InvalidConfigError,
    InvalidRunStateError,
    KBIndexError,
    KBItemNotFoundError,
    KeyStoreError,
    KnowledgeBaseError,
    MigrationError,
    MissingConfigError,
    ModelCapabilityError,
    ModelGatewayError,
    NetworkNotAllowedError,
    NoHealthyProviderError,
    OutputTooLargeError,
    PathNotAllowedError,
    ProviderHTTPError,
    RateLimitExceededError,
    RepositoryError,
    RunNotFoundError,
    RuntimeError,
    SecurityError,
    ServiceError,
    SessionNotFoundError,
    StorageError,
    UnhandledCallableError,
    UnknownFrameworkError,
)
from citnega.packages.shared.registry import BaseRegistry
from citnega.packages.shared.result import Err, Ok, Result

__all__ = [
    # Registry
    "BaseRegistry",
    # Result
    "Result",
    "Ok",
    "Err",
    # Errors
    "CitnegaError",
    "ConfigError",
    "MissingConfigError",
    "InvalidConfigError",
    "AdapterError",
    "UnknownFrameworkError",
    "AdapterInitError",
    "FrameworkRunnerError",
    "CallableError",
    "UnhandledCallableError",
    "CallableNotFoundError",
    "CallableValidationError",
    "CallablePolicyError",
    "CallableTimeoutError",
    "CallableDepthError",
    "PathNotAllowedError",
    "NetworkNotAllowedError",
    "OutputTooLargeError",
    "ApprovalDeniedError",
    "ApprovalTimeoutError",
    "ModelGatewayError",
    "NoHealthyProviderError",
    "RateLimitExceededError",
    "ProviderHTTPError",
    "ModelCapabilityError",
    "StorageError",
    "MigrationError",
    "RepositoryError",
    "ArtifactError",
    "KnowledgeBaseError",
    "KBItemNotFoundError",
    "KBIndexError",
    "RuntimeError",
    "SessionNotFoundError",
    "RunNotFoundError",
    "InvalidRunStateError",
    "ServiceError",
    "SecurityError",
    "KeyStoreError",
]
