"""
ScaffoldSpec + FallbackTemplates — static code generation for tools, agents, workflows.

FallbackTemplates is used when no model gateway is available.  Each render_*()
method returns a complete, importable Python module string with correct imports
for this codebase.  The generated code passes CodeValidator checks.
"""

from __future__ import annotations

from dataclasses import dataclass, field
import re


@dataclass
class ScaffoldSpec:
    """All information needed to render a single callable artifact."""

    kind: str  # "tool" | "agent" | "workflow"
    class_name: str  # PascalCase  e.g. "WebScraperTool"
    name: str  # snake_case  e.g. "web_scraper"
    description: str
    parameters: list[dict] = field(default_factory=list)  # [{"name","type","description"}]
    system_prompt: str = ""  # agents / workflows
    tool_whitelist: list[str] = field(default_factory=list)  # agent tool names
    sub_agents: list[str] = field(default_factory=list)  # workflow sub-agents


class FallbackTemplates:
    """
    Pure-static code generator — produces importable Python modules without an LLM.

    All three methods return a string that:
      - passes ``ast.parse()`` without error
      - contains a class named ``spec.class_name``
      - defines the required class-level attributes (name, description,
        callable_type, input_schema, output_schema, policy)
    """

    # ── helpers ───────────────────────────────────────────────────────────────

    @staticmethod
    def _indent(text: str, spaces: int = 4) -> str:
        pad = " " * spaces
        return "\n".join(pad + line if line.strip() else line for line in text.splitlines())

    @staticmethod
    def _param_fields(parameters: list[dict]) -> str:
        """Render pydantic Field declarations for each parameter."""
        if not parameters:
            return '    query: str = Field(description="Input to the tool.")'
        lines = []
        for p in parameters:
            pname = p.get("name", "value")
            ptype = p.get("type", "str")
            pdesc = p.get("description", "")
            lines.append(f"    {pname}: {ptype} = Field(description={pdesc!r})")
        return "\n".join(lines)

    @staticmethod
    def _param_names(parameters: list[dict]) -> list[str]:
        return [p.get("name", "query") for p in parameters] if parameters else ["query"]

    # ── public renderers ──────────────────────────────────────────────────────

    @classmethod
    def render_tool(cls, spec: ScaffoldSpec) -> str:
        """Render a complete tool module."""
        class_name = spec.class_name
        name = spec.name
        description = spec.description
        input_cls = f"{class_name}Input"
        param_fields = cls._param_fields(spec.parameters)
        param_names = cls._param_names(spec.parameters)
        result_expr = ' + ", " + '.join(f"str(input.{p})" for p in param_names)

        return f'''\
"""
{class_name} — user-created tool.
Generated by citnega /createtool.
"""

from __future__ import annotations

from pydantic import BaseModel, Field

from citnega.packages.protocol.callables.base import BaseCallable
from citnega.packages.protocol.callables.context import CallContext
from citnega.packages.protocol.callables.types import CallableType
from citnega.packages.tools.builtin._tool_base import ToolOutput, tool_policy


class {input_cls}(BaseModel):
{param_fields}


class {class_name}(BaseCallable):
    name          = {name!r}
    description   = {description!r}
    callable_type = CallableType.TOOL
    input_schema  = {input_cls}
    output_schema = ToolOutput
    policy        = tool_policy(timeout_seconds=30.0)

    async def _execute(self, input: {input_cls}, context: CallContext) -> ToolOutput:
        # TODO: implement your tool logic here
        result = {result_expr}
        return ToolOutput(result=result)
'''

    @classmethod
    def render_agent(cls, spec: ScaffoldSpec) -> str:
        """Render a complete specialist agent module."""
        class_name = spec.class_name
        name = spec.name
        description = spec.description
        input_cls = f"{class_name}Input"
        system_prompt = spec.system_prompt or f"You are a specialist agent: {description}"
        tool_whitelist_repr = repr(spec.tool_whitelist)

        return f'''\
"""
{class_name} — user-created specialist agent.
Generated by citnega /createagent.
"""

from __future__ import annotations

from pydantic import BaseModel, Field

from citnega.packages.agents.specialists._specialist_base import SpecialistBase, SpecialistOutput
from citnega.packages.protocol.callables.context import CallContext
from citnega.packages.protocol.callables.types import CallablePolicy, CallableType


class {input_cls}(BaseModel):
    task: str = Field(description="The task or question for this agent.")


class {class_name}(SpecialistBase):
    name          = {name!r}
    description   = {description!r}
    callable_type = CallableType.SPECIALIST
    input_schema  = {input_cls}
    output_schema = SpecialistOutput
    policy        = CallablePolicy(timeout_seconds=120.0, requires_approval=False)

    SYSTEM_PROMPT  = {system_prompt!r}
    TOOL_WHITELIST = {tool_whitelist_repr}

    async def _execute(self, input: {input_cls}, context: CallContext) -> SpecialistOutput:
        response = await self._call_model(input.task, context)
        return SpecialistOutput(response=response)
'''

    @classmethod
    def render_workflow(cls, spec: ScaffoldSpec) -> str:
        """Render a complete workflow orchestrator module."""
        class_name = spec.class_name
        name = spec.name
        description = spec.description
        input_cls = f"{class_name}Input"
        system_prompt = spec.system_prompt or (
            f"You are a workflow orchestrator. {description}. "
            "Co-ordinate the available agents and tools to complete the user's request."
        )
        tool_whitelist_repr = repr(spec.tool_whitelist + spec.sub_agents)

        return f'''\
"""
{class_name} — user-created workflow.
Generated by citnega /createworkflow.
"""

from __future__ import annotations

from pydantic import BaseModel, Field

from citnega.packages.agents.specialists._specialist_base import SpecialistBase, SpecialistOutput
from citnega.packages.protocol.callables.context import CallContext
from citnega.packages.protocol.callables.types import CallablePolicy, CallableType


class {input_cls}(BaseModel):
    objective: str = Field(description="High-level objective for this workflow.")


class {class_name}(SpecialistBase):
    name          = {name!r}
    description   = {description!r}
    callable_type = CallableType.SPECIALIST
    input_schema  = {input_cls}
    output_schema = SpecialistOutput
    policy        = CallablePolicy(timeout_seconds=300.0, requires_approval=False)

    SYSTEM_PROMPT  = {system_prompt!r}
    TOOL_WHITELIST = {tool_whitelist_repr}

    async def _execute(self, input: {input_cls}, context: CallContext) -> SpecialistOutput:
        response = await self._call_model(input.objective, context)
        return SpecialistOutput(response=response)
'''


def pascal_to_snake(name: str) -> str:
    """Convert PascalCase to snake_case.  e.g. WebScraperTool → web_scraper_tool"""
    s1 = re.sub(r"(.)([A-Z][a-z]+)", r"\1_\2", name)
    return re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", s1).lower()
